name: Merge PRs
on:
  pull_request:

jobs:
  automerge:
    name: Auto Merge
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: XNXKTech/workflows/.github/workflows/dependabot-auto-merge.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}